# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    
  

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - run: npm i
    - run: npm test


  packer_validate:
    runs-on: ubuntu-latest
    needs: build
    name: Validating Packer - AMI Build
    steps: 
      - name: Checkout code from branch
        uses: actions/checkout@v2

      - name: Zip webapp 
        run: |
          zip -r webapp.zip ./
          ls   

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.8.3" # or `latest`
          
      - name: Run `packer init`
        id: init
        run: "packer init ./aws.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./aws.pkr.hcl"
