name: Validating Packer AMI template
on:
  workflow_dispatch:
  pull_request:
    branches: ["main"] 

jobs:      
  packer_validate:
    runs-on: ubuntu-latest
    name: Validating Packer - AMI Build
    steps: 
      - name: Step 1 - Checkout code from branch
        uses: actions/checkout@v2

      - name: Step 2 - Zip webapp 
        run: |
           zip -r webapp.zip ./
           ls  

      - name: Step 3 - Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.8.3" # or `latest`
          
      - name: Step 4 - Run `packer init`
        id: init
        run: "packer init ./aws.pkr.hcl"

      - name: Step 5 - Run `packer validate`
        id: validate
        run: "packer validate --var-file=aws.pkrvars.hcl ./aws.pkr.hcl"