name: Validating Packer AMI template
on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

jobs:      
  packer_validate:
    runs-on: ubuntu-latest
    name: Validating Packer - AMI Build
    steps: 
      - name: Checkout code from branch
        uses: actions/checkout@v2

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.8.3" # or `latest`
          
      - name: Run `packer init`
        id: init
        run: "packer init ./aws.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./aws.pkr.hcl"